# Generated by Django 5.2.1 on 2025-05-12 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_client_owner_mailing_owner_mailingattempt_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='mailing',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='mailingattempt',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='message',
            name='owner',
        ),
    ]
