# Generated by Django 5.2.1 on 2025-05-12 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0004_client_owner_mailing_owner_mailingattempt_owner_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailingattempt",
            name="date_attempt",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата попытки"),
        ),
    ]
