# Generated by Django 5.2.1 on 2025-05-13 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0007_alter_message_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={
                "ordering": ["title"],
                "permissions": [("view_all_mailings", "Can view all mailings")],
                "verbose_name": "письмо",
                "verbose_name_plural": "письма",
            },
        ),
    ]
