# Generated by Django 5.2.1 on 2025-05-13 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0009_alter_mailingattempt_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={
                "ordering": ["full_name"],
                "permissions": [
                    ("can_disable_mailing", "Can disable mailing"),
                    ("view_all_clients", "Can view all clients"),
                ],
                "verbose_name": "получатель",
                "verbose_name_plural": "получатели",
            },
        ),
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "ordering": ["start_sending"],
                "permissions": [
                    ("can_disable_mailing", "Can disable mailing"),
                    ("view_all_mailings", "Can view all mailings"),
                ],
                "verbose_name": "рассылка",
                "verbose_name_plural": "рассылки",
            },
        ),
        migrations.AlterModelOptions(
            name="message",
            options={
                "ordering": ["title"],
                "verbose_name": "письмо",
                "verbose_name_plural": "письма",
            },
        ),
    ]
