# Generated by Django 5.2.1 on 2025-05-13 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0010_alter_client_options_alter_mailing_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={
                "ordering": ["full_name"],
                "permissions": [("view_all_clients", "Can view all clients")],
                "verbose_name": "получатель",
                "verbose_name_plural": "получатели",
            },
        ),
    ]
